### ISSUE TITLE
How can import to angular 6 component

### ISSUE THREAD

**Issue by enaide** [kluverua/Chartjs-tsgauge#1]
Please somebody help me, how can import this components for angular 6, with out import form index.html directly  bat from particular component

this component look perfect for me.

**Comment by kluverua** [comment]
Can you try to copy this code and paste it right after the main chartjs library code?

**Comment by enaide** [comment]
yes bat don't working throw exception

**Comment by kluverua** [comment]
Send me file that throw exception and all depend files

**Comment by artem-galas** [comment]
@enaide 
You have to add `Gauge.js` to you project (any directory)
Then you have to extend `ChartDataSets` and `ChartOptions` interfaces. For that - create file `chartjst-extention.d.ts` and put next code:

```d.ts
import { Chart, ChartDataSets, ChartOptions } from 'chart.js';

declare module 'chart.js' {
  interface ChartDataSets {
    gaugeData?: any;
    gaugeLimits?: any;
  }

  interface ChartOptions {
    showMarkers?: boolean;
  }
}
```

In your component  import CharJs and Gauge.js
for example

```ts
import { Chart } from 'chart.js';
export * from '~/framework/util/Gauge';
```
